import Link from 'next/link'
export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white text-zinc-900 py-20 px-6">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-sm font-medium text-zinc-400 hover:text-black mb-8 inline-block">← Back to Home</Link>
        <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
        <div className="prose prose-zinc text-zinc-600 space-y-6">
          <p>Last updated: September 12, 2026</p>
          <p>Welcome to Veloceia ("Veloceia," "we," "us," or "our"). Veloceia is an AI-powered scheduling and client-communication platform for salons and service businesses. This website and the Veloceia services (the "Service") are operated and legally owned by Dong Wei Wang, a Sole Proprietor.</p>
          <p>This Privacy Policy explains what information we collect, how we use it, and the choices you have regarding your information.</p>

          <h2 className="text-xl font-semibold text-black mt-8">1. Information We Collect</h2>
          <p><strong>Account information.</strong> When you create an account, we collect your name, email address, and password (stored in encrypted form).</p>
          <p><strong>Client data.</strong> To provide our scheduling and communication features, we collect information you input about your own clients, including their names and phone numbers, appointment details, and any notes you add.</p>
          <p><strong>Voice data.</strong> When you use our voice memo feature, we collect the audio you record and the text generated from transcribing that audio.</p>
          <p><strong>SMS communications.</strong> We collect the content and metadata of text messages sent and received through the Service, including messages generated by our AI on your behalf and client replies.</p>
          <p><strong>Usage information.</strong> We may collect information about how you access and use the Service, such as login timestamps, device/browser type, and IP address.</p>

          <h2 className="text-xl font-semibold text-black mt-8">2. How We Use Your Information</h2>
          <p>We use the information described above to provide, operate, and maintain the Service, including appointment scheduling and client management; convert voice memos to text; generate and send AI-drafted SMS replies to your clients on your behalf; monitor and improve performance, security, and reliability; communicate with you about your account; and comply with legal obligations.</p>
          <p>We do not sell your personal information or your clients' personal information to third parties.</p>

          <h2 className="text-xl font-semibold text-black mt-8">3. How We Share Your Information</h2>
          <p>We share information only with service providers that help us operate the Service, under contractual obligations restricting them from using it for their own purposes: Twilio (to send and receive SMS on your behalf), Supabase (to securely host application data), and AI/language model providers (to process voice-to-text and generate SMS reply drafts).</p>
          <p>No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. All other categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>

          <h2 className="text-xl font-semibold text-black mt-8">4. Data Retention</h2>
          <p>We retain your account and client data for as long as your account remains active. If you close your account, we will delete or anonymize your personal information within a reasonable period, except where retention is required by law or to resolve disputes.</p>

          <h2 className="text-xl font-semibold text-black mt-8">5. Your Rights and Choices</h2>
          <p>You may contact us at any time to request access to, correction of, or deletion of your personal information, or your clients' personal information you've entered into the Service. You may also opt out of SMS at any time by replying "STOP" to any text message.</p>

          <h2 className="text-xl font-semibold text-black mt-8">6. Data Security</h2>
          <p>We implement appropriate technical and organizational measures to protect your information, including encrypted data transmission (HTTPS/TLS), encrypted password storage, and access controls limiting who can view stored data.</p>

          <h2 className="text-xl font-semibold text-black mt-8">7. International Data Transfer</h2>
          <p>Veloceia is operated from China; however, our service providers (including Twilio and our hosting infrastructure) may process and store data in the United States or other countries. By using the Service, you understand your information may be transferred to and processed in a country other than your own.</p>

          <h2 className="text-xl font-semibold text-black mt-8">8. Children's Privacy</h2>
          <p>The Service is not directed to individuals under the age of 13, and we do not knowingly collect personal information from children under 13.</p>

          <h2 className="text-xl font-semibold text-black mt-8">9. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. If we make material changes, we will update the "Last updated" date above and, where appropriate, notify you directly.</p>

          <h2 className="text-xl font-semibold text-black mt-8">10. Contact Us</h2>
          <p>If you have any questions about this Privacy Policy or wish to exercise your data rights, please contact us at <strong>support@veloceia.com</strong>.</p>

          <h2 className="text-xl font-semibold text-black mt-8">11. Company Information</h2>
          <p>
            Veloceia<br />
            No. 55 Xujiahuan, Jinniu Sector, Wuzhen,<br />
            Tongxiang, Zhejiang, China, 314501
          </p>
        </div>
      </div>
    </div>
  )
}
